"""Domain types. Money and fiscal dates are strings; extra keys are refused."""

from poarta_contabila.types.base import (
    Closed,
    Cui,
    FiscalDate,
    Money,
    Period,
    Rate,
    Slug,
    cui_is_valid,
    cui_key,
)
from poarta_contabila.types.models import (
    AccountDelta,
    BucketRow,
    CanonicalDocument,
    ControlRun,
    DocClass,
    ExpectedItem,
    FilingItem,
    JobRecord,
    JobStatus,
    Line,
    PartnerRef,
    PeriodDiff,
    PrimaryKind,
    SinkDoc,
    SourceRef,
    TenantRef,
    Totals,
    WriteModule,
)

__all__ = [
    "AccountDelta",
    "BucketRow",
    "CanonicalDocument",
    "Closed",
    "ControlRun",
    "Cui",
    "DocClass",
    "ExpectedItem",
    "FilingItem",
    "FiscalDate",
    "JobRecord",
    "JobStatus",
    "Line",
    "Money",
    "PartnerRef",
    "Period",
    "PeriodDiff",
    "PrimaryKind",
    "Rate",
    "SinkDoc",
    "Slug",
    "SourceRef",
    "TenantRef",
    "Totals",
    "WriteModule",
    "cui_is_valid",
    "cui_key",
]
